---
- hosts: localhost
  remote_user: vagrant
  vars_files: vars.yml
    
  tasks:
    - name : install software 
      package :
        name : "{{item}}"
        state : present
      loop : "{{packages}}"

    - name: Seeting up PS1  
      blockinfile:
        path: /home/{{user}}/.bashrc
        block: |
          # PS1 setup
          export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$"
          
    # to do
    # ZSH setup 