---
- hosts: localhost
  remote_user: vagrant
  vars_files: vars.yml
    
  tasks:
    - name : install software 
      package :
        name : "{{item}}"
        state : present
      loop : "{{packages}}"

    - name: Configure bashrc by adding tmux and PS1
      blockinfile:
        path: /home/{{user}}/.bashrc
        block: |
          # setup TMUX on login
          if [ -z "$TMUX" ]; then
          tmux attach -t default || tmux new -s default
          fi

          # PS1 setup
          export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$"

    - name: Download vim config
      get_url:
        url: https://raw.githubusercontent.com/linuxacademy/content-python3-sysadmin/master/helpers/vimrc
        dest: /home/{{user}}/.vimrc
